# Define enviroment
- hosts: localhost
  roles:     
    - role: 01_define_enviroment  

# Clear everything
- hosts: hypervisor
  user: root
  roles:     
    - role: 02_remove_all

# Create everything
- hosts: hypervisor
  user: root
  roles:     
    - role: 03_create

# Update nodes:
- hosts: nodes
  user: root
  roles:     
    - role: 04_update
